name: task_management_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.0
  cupertino_icons: ^1.0.8
  intl: ^0.17.0  # Adding intl package
  sqflite: ^2.0.0+4
  path: ^1.8.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  flutter_local_notifications: ^17.2.4
  table_calendar: ^3.0.0
  theme_provider: ^0.6.0
  provider: ^6.1.2
  path_provider: ^2.0.11
  pdf: ^3.8.0
  flutter_downloader: ^1.8.3
  permission_handler: ^10.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.1.4
  hive_generator: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/task_management_app_peach_pencil_image.png"  # Image path for your icon

flutter:
  uses-material-design: true

  # Adding assets section
  assets:
    - assets/  # Image path for assets
